"""Bridge to agentbastion / bastiongate: turn a skill scan into a policy.

Closes the trilogy loop the same way the sibling tools' `harden` do. A scan of a
skill produces a per-skill verdict (allow/deny) plus the capabilities that tripped
the deny, ready to drop into the firewall's skill policy.
"""

from __future__ import annotations

from .models import ScanReport

_BLOCK = {"critical", "high"}


def to_policy_yaml(report: ScanReport) -> str:
    tripped = [f for f in report.findings if f.severity in _BLOCK]
    verdict = "deny" if tripped else "allow"
    reasons = sorted({f.check for f in tripped})
    caps = sorted({f.capability for f in tripped if f.capability})

    lines = [
        "# agentbastion / bastiongate skill policy generated by bastionskill",
        f"# skill: {report.skill}  risk={report.risk}",
        "default: allow",
        "skills:",
        f"  {_q(report.skill)}:",
        f"    verdict: {verdict}",
    ]
    if reasons:
        lines.append("    reasons:")
        lines += [f"      - {r}" for r in reasons]
    if caps:
        lines.append("    block_capabilities:")
        lines += [f"      - {c}" for c in caps]
    return "\n".join(lines) + "\n"


def _q(name: str) -> str:
    if name and all(c.isalnum() or c in "_-." for c in name):
        return name
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'
