"""Turn a skill scan into a `policy_version: 2` skill verdict.

The verdict (allow/deny, the checks and capabilities that tripped it, and the
`digest` of the exact files vetted) goes in the `skill:` block the shared v2 format
reserves for bastionskill. `bastionskill install --policy` enforces it. agentbastion
and bastiongate don't run skills, so they load the file (valid v2) and leave the block
alone; the file installs no tool policy in either, so it can't loosen one by accident.
"""

from __future__ import annotations

from .models import ScanReport


def to_policy_yaml(report: ScanReport, digest: str | None = None) -> str:
    return to_policy_yaml_many([(report, digest)])


def to_policy_yaml_many(items: list[tuple[ScanReport, str | None]]) -> str:
    """One verdict file for one or more skills. `digest` (loader.tree_digest) pins
    each verdict to the exact files vetted; `bastionskill install` enforces it."""
    names = [r.skill for r, _ in items]
    dupes = sorted({n for n in names if names.count(n) > 1})
    if dupes:
        raise ValueError(f"two skills share a name: {dupes}; rename one or harden them separately")
    lines = [
        "# skill verdict generated by bastionskill, enforced by `bastionskill install --policy`.",
        "# agentbastion / bastiongate load this file but don't enforce the skill: block.",
        (f"# skill: {items[0][0].skill}  risk={items[0][0].risk}" if len(items) == 1
         else f"# skills: {len(items)}"),
        "policy_version: 2",
        "skill:",
        "  skills:",
    ]
    for report, digest in items:
        lines += _entry(report, digest)
    return "\n".join(lines) + "\n"


def _entry(report: ScanReport, digest: str | None) -> list[str]:
    # v0.2: deny on the verdict (malice/shadow), not on raw capability severity.
    tripped = [f for f in report.findings if f.kind in ("malice", "shadow")]
    verdict = "allow" if report.verdict == "allow" else "deny"
    reasons = sorted({f.check for f in tripped})
    caps = sorted({f.capability for f in tripped if f.capability})
    lines = [f"    {_q(report.skill)}:", f"      verdict: {verdict}"]
    if digest:
        lines.append(f"      digest: {digest}")
    if reasons:
        lines.append("      reasons:")
        lines += [f"        - {r}" for r in reasons]
    if caps:
        lines.append("      block_capabilities:")
        lines += [f"        - {c}" for c in caps]
    return lines


def _q(name: str) -> str:
    if name and all(c.isalnum() or c in "_-." for c in name):
        return name
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'
