"""Turn a skill scan into a `policy_version: 2` skill verdict.

The verdict (allow/deny, the checks and capabilities that tripped it) goes in the
`skill:` block the shared v2 format reserves for bastionskill. It is for whatever
installs or loads skills: a CI step, a loader, a review. agentbastion and bastiongate
don't run skills, so they load the file (valid v2) and leave the block alone; the
file installs no tool policy in either, so it can't loosen one by accident.
"""

from __future__ import annotations

from .models import ScanReport


def to_policy_yaml(report: ScanReport) -> str:
    # v0.2: deny on the verdict (malice/shadow), not on raw capability severity.
    tripped = [f for f in report.findings if f.kind in ("malice", "shadow")]
    verdict = "allow" if report.verdict == "allow" else "deny"
    reasons = sorted({f.check for f in tripped})
    caps = sorted({f.capability for f in tripped if f.capability})

    lines = [
        "# skill verdict generated by bastionskill, for skill loaders and CI.",
        "# agentbastion / bastiongate load this file but don't enforce the skill: block.",
        f"# skill: {report.skill}  risk={report.risk}",
        "policy_version: 2",
        "skill:",
        "  skills:",
        f"    {_q(report.skill)}:",
        f"      verdict: {verdict}",
    ]
    if reasons:
        lines.append("      reasons:")
        lines += [f"        - {r}" for r in reasons]
    if caps:
        lines.append("      block_capabilities:")
        lines += [f"        - {c}" for c in caps]
    return "\n".join(lines) + "\n"


def _q(name: str) -> str:
    if name and all(c.isalnum() or c in "_-." for c in name):
        return name
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'
